default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: albatross_development
  host: 127.0.0.1
  port: 5434
  username: albatross_user

test:
  <<: *default
  database: albatross_test
  host: 127.0.0.1
  port: 5434
  username: albatross_user

production:
  <<: *default
  database: albatross_production
  username: albatross
  password: <%= ENV["ALBATROSS_DATABASE_PASSWORD"] %>
