# .github/workflows/ruby.yml
name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_USER: rails_github_actions
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev libvips
          bundle install --jobs 4 --retry 3
      - name: Run Specs
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_USER: rails_github_actions
          POSTGRES_PASSWORD: postgres
          CI: true
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:schema:load
          bundle exec rails assets:precompile
          bundle exec rails test
